In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib
import csv
from datetime import datetime
import time

In [2]:
i = 1
while i < 5:
    print('value {}'. format(i))
    i = i+1
else:
    print('exit')

value 1
value 2
value 3
value 4
exit


In [3]:
my_list = [1,2,3,4,5]
for item in my_list:
    print(item)

1
2
3
4
5


In [4]:
for num in my_list:
    print('Hi')

Hi
Hi
Hi
Hi
Hi


In [5]:
for num in my_list:
    print(num**2)

1
4
9
16
25


In [6]:
list(range(5))

[0, 1, 2, 3, 4]

In [7]:
for i in range(5):
    print(i)

0
1
2
3
4


In [8]:
for i in range(3,5):
    print (i)

3
4


In [9]:
for i in range(1,10,2):
    print (i)

1
3
5
7
9


In [10]:
x = [2,3,4,5]
out = []
for num in x:
    out.append(num**2)
print(out)

[4, 9, 16, 25]


In [11]:
[num**2 for num in x]

[4, 9, 16, 25]

In [12]:
[chars for chars in 'hi jeff']

['h', 'i', ' ', 'j', 'e', 'f', 'f']

In [13]:
[num**2 for num in range(2,10)]

[4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
def func_name(param1):
    print(param1)
    print(param1 + ', this is Python')

func_name('Hi')

Hi
Hi, this is Python


In [15]:
def func_name(param1 = 'default value'):
    print(param1)
    print(param1 + ', this is Python')

func_name()

default value
default value, this is Python


In [16]:
func_name('Hi')

Hi
Hi, this is Python


In [17]:
def my_func(num1, num2):
    num = num1*num2
    return num

my_func(2,3)

6

In [18]:
y = my_func(2,3)
y

6

In [19]:
def my_func(num1, num2):
    """
    this function is returning the multiplication of two numbers
    """
    num = num1*num2
    return num

In [20]:
def sq_num(num):
    return num**2

sq_num(4)

16

In [21]:
def sq_num(num):return num**2

In [22]:
lambda num:num**2

<function __main__.<lambda>(num)>

In [23]:
x = [1,2,3,4,5]
y = []
for num in x:
    y.append(num**2)
print(y)

[1, 4, 9, 16, 25]


In [24]:
result = map(sq_num,x)

In [25]:
result = map(sq_num,x)

In [26]:
list(result)

[1, 4, 9, 16, 25]

In [27]:
list(map(lambda num:num**2, x))

[1, 4, 9, 16, 25]

In [28]:
a = [1,2,3,4]
b = [17,12,11,10]
c = [-1,-4,5,9]

list(map(lambda x,y,z: x+y+z, a,b,c))

[17, 10, 19, 23]

In [29]:
list(filter(lambda num:num%2==0, range(1,10)))

[2, 4, 6, 8]

In [30]:
my_list = [-1,0,1]

In [32]:
my_list, type(my_list)

([-1, 0, 1], list)

In [34]:
my_array = np.array(my_list)

In [35]:
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [36]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [37]:
my_matrix, type(my_matrix)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [38]:
matrix_one = np.array(my_matrix)

In [39]:
matrix_one, type(matrix_one)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [40]:
my_tuple = (-1,0,1)
my_array_tuple = np.array(my_tuple)

In [41]:
my_array_tuple, type(my_array_tuple)

(array([-1,  0,  1]), numpy.ndarray)

In [42]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [43]:
np.arange(0,11,2, dtype = float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [44]:
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [45]:
np.linspace(1,15,15,retstep = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.]),
 1.0)

In [47]:
np.linspace(1,15,30,retstep = True)

(array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
         3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
         5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
         8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
        10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
        13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ]),
 0.4827586206896552)

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand(3)

array([0.99105689, 0.19901925, 0.58047597])

In [58]:
np.random.rand(3,2)

array([[0.21482722, 0.46335682],
       [0.51934418, 0.23600483],
       [0.25933883, 0.15224043]])

In [59]:
np.random.randn(3,2)

array([[ 1.31766316, -0.92096502],
       [-0.9509024 ,  1.08854801],
       [-1.48534123, -0.0024732 ]])

In [61]:
np.random.randint(1,100)

15

In [62]:
np.random.randint(1,100,10)

array([40, 91, 39, 13, 95, 23, 26, 19, 10, 15])

In [65]:
np.random.randint(1,100,(4,4))

array([[25, 97, 34, 34],
       [63, 59, 54, 22],
       [91, 50, 32, 59],
       [83, 27, 92, 99]])

In [66]:
##Array of integers from 0-15
array_arange = np.arange(16)

In [68]:
###Array of 10 random integers from 0-100
array_ranint = np.random.randint(0,100,10)

In [72]:
array_arange

array_ranint

array([76, 86, 68,  0, 74, 42, 90, 60,  6, 17])

In [70]:
##Reshape random array to 4x4 matrix
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
##Lowest element in the array
array_ranint.min()

0

In [74]:
##Highest element in the array
array_ranint.max()

90

In [76]:
##Index position of highest element of the array
array_ranint.argmax()

6

In [77]:
##Index position of Lowest element of the array
array_ranint.argmin()

3

In [79]:
##size, shape, data type of array
array_arange.shape

(16,)

In [80]:
##size, shape, data type of array
array_arange.size

16

In [81]:
##size, shape, data type of array
array_arange.dtype

dtype('int64')

In [83]:
##reshape array
array_arange.reshape(4,4).shape

(4, 4)

In [84]:
array_1d = np.array(([-10,2,0,2,17,106,200]))

In [85]:
array_1d

array([-10,   2,   0,   2,  17, 106, 200])

In [86]:
array_1d[0]

-10

In [87]:
###Slice array using index
array_1d[0:3]

array([-10,   2,   0])

In [88]:
## Second to last item in the array
array_1d[-2]

106

In [89]:
array_1d[:2]

array([-10,   2])

In [90]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [94]:
array_2d = np.arange(24).reshape(6,4)

In [96]:
array_2d[2,2]

10

In [98]:
array_2d[1]

array([4, 5, 6, 7])

In [99]:
row = 2
col = 3
array_2d[row,col]

11

In [100]:
array_2d[2:4,2:4]

array([[10, 11],
       [14, 15]])

In [101]:
###Broadcasting
array_1d = np.arange(0,10)
array_1d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
array_1d[0:5] = 500
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [105]:
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [108]:
arr = np.arange(0,4)
array_2d + arr

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [109]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [110]:
array_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [111]:
arr

array([0, 1, 2, 3])

In [114]:
arr2=np.arange(0,4)[:,np.newaxis]

In [115]:
arr2

array([[0],
       [1],
       [2],
       [3]])

In [116]:
arr2+arr

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [117]:
###Fancy Indexing

In [119]:
array_2d = np.zeros((5,5))
array_2d.shape[1]
for i in range(array_2d.shape[1]):
    array_2d[i] = i
array_2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [124]:
array_2d[[1,2,3]]

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [125]:
array_2d[[3,0,1]]

array([[3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [126]:
array_2d = np.arange(24)

In [127]:
array_2d.shape = (6,4)

In [128]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [129]:
array_2d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [130]:
array_2d[[5,0]]

array([[20, 21, 22, 23],
       [ 0,  1,  2,  3]])

In [132]:
array_2d[:,[2,3]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [133]:
array_2d[:,[3,0]]

array([[ 3,  0],
       [ 7,  4],
       [11,  8],
       [15, 12],
       [19, 16],
       [23, 20]])

In [136]:
###Boolean Mask
arr_1 = np.arange(1,11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
bool_mask = arr_1>3

In [142]:
arr_1[bool_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [143]:
mod_2_mask_id = 0 == arr_1 % 2

In [144]:
mod_2_mask_id

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [145]:
ev_val = arr_1[mod_2_mask_id]
ev_val

array([ 2,  4,  6,  8, 10])

In [146]:
arr_1[arr_1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [147]:
array_2d = np.arange(24)
array_2d.shape = (6,4)
mod_2_mask_2d = 0 == array_2d % 2

In [148]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [149]:
mod_2_mask_2d

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [154]:
array_2d[mod_2_mask_2d]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
###Array Arithmetic

In [155]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [156]:
arr+arr

array([0, 2, 4, 6, 8])

In [157]:
arr*arr

array([ 0,  1,  4,  9, 16])

In [159]:
1/arr

/var/folders/b6/l1n962ss59n521_0vxpckrcr0000gn/T/ipykernel_36476/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [160]:
2*arr

array([0, 2, 4, 6, 8])

In [161]:
10*arr

array([ 0, 10, 20, 30, 40])

In [162]:
###Array Universal Functions
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [163]:
np.max(arr)

4

In [164]:
np.min(arr)

0

In [165]:
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [166]:
np.deg2rad(arr)

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317])

In [167]:
np.rad2deg(np.deg2rad(arr))

array([0., 1., 2., 3., 4.])

In [5]:
from datetime import datetime
from datetime import timedelta
import time
delta = timedelta(hours=1)
delta_minutes = timedelta(minutes=10)
now = datetime.now()
next_hour = (now + delta).replace(microsecond=0, second=0, minute=0)
next_minute = (now + delta_minutes)

wait_seconds = (next_hour - now).seconds
wait_seconds_minutes = (next_minute - now).seconds

#time.sleep(wait_seconds_minutes)

In [6]:
wait_seconds_minutes

600

In [7]:
next_minute

datetime.datetime(2023, 8, 5, 14, 4, 11, 867762)